//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Event { get; set; }
        public System.DateTime Date { get; set; }
        public double SSCcriteria { get; set; }
        public double HSCcriteria { get; set; }
        public double CGPA { get; set; }
        public string Website { get; set; }
    }
}
