//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class admin
    {
        public int id { get; set; }
        public string company_name { get; set; }
        public string @event { get; set; }
        
        [DataType(DataType.Date)]
        public DateTime? date { get; set; }
        public double C10th_criteria { get; set; }
        public double C12th_criteria { get; set; }
        public double CPGA { get; set; }
        public string website { get; set; }
    }
}
