//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public int Rollno { get; set; }
        public int Semester { get; set; }
        public double SSC { get; set; }
        public double HSC { get; set; }
        public double CGPA { get; set; }
        public int Backlogs { get; set; }
        public long PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public string Photo { get; set; }
        public string Resume { get; set; }
        public string Address { get; set; }
    }
}
